const fs = require('fs');
const path = require('path');

const MANIFEST_PATH = path.join(__dirname, '../assets/upload_manifest.json');
const METADATA_TS_PATH = path.join(__dirname, '../utils/MonsterMetadata.ts');

function run() {
    if (!fs.existsSync(MANIFEST_PATH)) {
        console.error("❌ upload_manifest.json not found. Run upload_to_irys.js first.");
        return;
    }

    const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf-8'));
    const ids = Object.keys(manifest).sort((a, b) => parseInt(a) - parseInt(b));

    process.stdout.write(`🧬 Finalizing MonsterMetadata.ts with ${ids.length} items...`);

    let tsContent = `// AUTO-GENERATED BY scripts/finalize_monster_metadata.js\n`;
    tsContent += `// DO NOT EDIT MANUALLY\n\n`;

    tsContent += `export const MONSTER_IDS = [\n    ${ids.map(id => `'${id}'`).join(',\n    ')}\n];\n\n`;

    tsContent += `export const MONSTER_URIS: { [key: string]: string } = {\n`;
    ids.forEach(id => {
        tsContent += `    '${id}': '${manifest[id].jsonUri}',\n`;
    });
    tsContent += `};\n`;

    fs.writeFileSync(METADATA_TS_PATH, tsContent);
    console.log(`\n✅ Successfully updated ${METADATA_TS_PATH}`);
}

run();
